\chapter{Require a message for \texorpdfstring{$<$}{<}tt\texorpdfstring{$>$}{>}to\+Throw()\texorpdfstring{$<$}{<}/tt\texorpdfstring{$>$}{>} (\texorpdfstring{$<$}{<}tt\texorpdfstring{$>$}{>}require-\/to-\/throw-\/message\texorpdfstring{$<$}{<}/tt\texorpdfstring{$>$}{>})}
\hypertarget{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message}{}\label{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message}\index{Require a message for $<$tt$>$toThrow()$<$/tt$>$ ($<$tt$>$require-\/to-\/throw-\/message$<$/tt$>$)@{Require a message for $<$tt$>$toThrow()$<$/tt$>$ ($<$tt$>$require-\/to-\/throw-\/message$<$/tt$>$)}}
\label{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11478}%
\Hypertarget{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11478}%
 {\ttfamily to\+Throw()} (and its alias {\ttfamily to\+Throw\+Error()}) is used to check if an error is thrown by a function call, such as in {\ttfamily expect(() =\texorpdfstring{$>$}{>} a()).to\+Throw()}. However, if no message is defined, then the test will pass for any thrown error. Requiring a message ensures that the intended error is thrown.\hypertarget{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11479}{}\doxysection{\texorpdfstring{Rule details}{Rule details}}\label{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11479}
This rule triggers a warning if {\ttfamily to\+Throw()} or {\ttfamily to\+Throw\+Error()} is used without an error message.\hypertarget{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11480}{}\doxysubsection{\texorpdfstring{Default configuration}{Default configuration}}\label{md_node__modules_2eslint-plugin-jest_2docs_2rules_2require-to-throw-message_autotoc_md11480}
The following patterns are considered warnings\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{test('all\ the\ things',\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ expect(()\ =>\ a()).toThrow();}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ expect(()\ =>\ a()).toThrowError();}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ await\ expect(a()).rejects.toThrow();}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ await\ expect(a()).rejects.toThrowError();}
\DoxyCodeLine{\});}

\end{DoxyCode}


The following patterns are not considered warnings\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{test('all\ the\ things',\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ expect(()\ =>\ a()).toThrow('a');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ expect(()\ =>\ a()).toThrowError('a');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ await\ expect(a()).rejects.toThrow('a');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ await\ expect(a()).rejects.toThrowError('a');}
\DoxyCodeLine{\});}

\end{DoxyCode}
 